#!/bin/sh

# This script is used with test-gnupg-process
set -euf

while getopts '1:2:' arg; do
	case $arg in
	1)
		echo $OPTARG
		;;
	2)
		echo $OPTARG
		;;
	*)
		echo "invalid argument: $arg"
		exit 2
		;;
	esac
done

printf $ENVIRON1 >&2
echo $ENVIRON2 >&2
